table Sales
	lineageTag: b2745cd6-91f3-408f-8f88-d9e68e5aac72
	sourceLineageTag: c90c54c3-ecc7-4006-acae-213e629b2b9e

	measure Profit = EXTERNALMEASURE("Profit", CURRENCY, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4cabdb5a-f61d-416b-a72c-70ec1112f71e
		sourceLineageTag: e9392e16-8287-4a63-8f98-14ddbc88ec6d
		dataCategory: Uncategorized

	measure 'Profit Margin' = EXTERNALMEASURE("Profit Margin", DOUBLE, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 5724dd55-bfa8-4814-baf0-ca201489b732
		sourceLineageTag: 6dcf0ce0-a21f-454e-8857-7bf5e2b7b031
		dataCategory: Uncategorized

	measure 'Avg Price' = EXTERNALMEASURE("Avg Price", CURRENCY, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: 06478fba-a8d8-45a7-88fb-9a34341f961d
		sourceLineageTag: 9ca76f2a-b132-4cb0-813c-f4e65d5f9c71
		dataCategory: Uncategorized

	measure 'Median Price' = EXTERNALMEASURE("Median Price", CURRENCY, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: cdf3085a-0fe8-4f82-b57e-b0650d02b8f9
		sourceLineageTag: 22c94527-a543-4638-8cf7-fb934808620e
		dataCategory: Uncategorized

	measure 'Min Price' = EXTERNALMEASURE("Min Price", CURRENCY, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: 3b2752a6-a71c-4b08-b801-82a08efcf01c
		sourceLineageTag: 94d285a5-58ae-40fb-98dd-29b64a058507
		dataCategory: Uncategorized

	measure 'Max Price' = EXTERNALMEASURE("Max Price", CURRENCY, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: f9755eb9-5f31-4e6c-9107-3e5661b4ae2a
		sourceLineageTag: 793f0df1-015b-4908-b5bd-aefbd1dfdb62
		dataCategory: Uncategorized

	measure Orders = EXTERNALMEASURE("Orders", INTEGER, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: 0
		displayFolder: Counts
		lineageTag: b4a894cc-edf8-4928-a16a-9ab60f42a2c2
		sourceLineageTag: 57f38fd6-cf9a-4d06-a7ee-1a306043c61b
		dataCategory: Uncategorized

	measure 'Order Lines' = EXTERNALMEASURE("Order Lines", INTEGER, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: 0
		displayFolder: Counts
		lineageTag: cb6f8cf6-9396-4758-aad4-b5e8402bf04c
		sourceLineageTag: da03adc1-acfb-4d73-9aaa-b5e373c5e88f
		dataCategory: Uncategorized

	measure 'Sales % All Region' = EXTERNALMEASURE("Sales % All Region", DOUBLE, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Ratios
		lineageTag: 538976bf-ad1e-4938-9e04-bd4b176a05fe
		sourceLineageTag: 008e9ca5-2758-43de-9595-76282e69f31d
		dataCategory: Uncategorized

	measure 'Sales % Country' = EXTERNALMEASURE("Sales % Country", DOUBLE, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Ratios
		lineageTag: 822e065b-5b15-4f25-a23b-dab098eca878
		sourceLineageTag: 954e603d-5c04-4a90-ad4c-8f34b04ea323
		dataCategory: Uncategorized

	measure 'Sales % Group' = EXTERNALMEASURE("Sales % Group", DOUBLE, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		displayFolder: Ratios
		lineageTag: e14eec3f-ea3a-4548-a57b-996a97d7b5c1
		sourceLineageTag: 565a0642-ff70-4055-95e3-f5233d204ae8
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales YTD' = EXTERNALMEASURE("Sales YTD", CURRENCY, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Time Intelligence
		lineageTag: b7ffcd30-053d-496c-9b11-42c355450fc0
		sourceLineageTag: a9440108-f6a0-4e23-b6c9-9fa7662ff79b
		dataCategory: Uncategorized

	measure 'Sales YoY Growth' = EXTERNALMEASURE("Sales YoY Growth", DOUBLE, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time Intelligence
		lineageTag: d75c25ef-1745-41c1-a3d7-9747c13e48ab
		sourceLineageTag: 5e215bb9-dc07-4caa-a171-431cb225e29a
		dataCategory: Uncategorized

	measure 'Sales per Capita' = ```
			
			 DIVIDE(
			     SUM(Sales[Sales]),
			     SUM('US Population'[Population])
			 )
			```
		formatString: 0
		lineageTag: 6917a0cb-fdf1-475c-8d78-33008086dcfc

		changedProperty = Name

	column SalesOrderNumber
		dataType: string
		isHidden
		lineageTag: b3a8bd36-a2e4-45a3-b6ae-5bbc3ec04d4c
		sourceLineageTag: f7a951a1-052d-44bb-911c-0f487977d8e6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = User

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: e5356511-f1a4-4deb-b027-58564bf8f796
		sourceLineageTag: f09e25ae-d1b9-4233-80a0-f947efe49834
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = User

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e961a2cf-ba25-4f6e-9e3c-b5324117158d
		sourceLineageTag: 322e241e-6244-4cd7-bb79-bf30ad967c85
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = User

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 50d8bac5-19ef-4b62-8936-2a97c2bab091
		sourceLineageTag: fa69a045-873a-49b5-847a-2eda5565fab7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = User

	column EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 99a48e69-3278-487b-bb8f-999722d0c1c6
		sourceLineageTag: 84ab0fd3-0c83-4456-a495-f0e3817be1b3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = User

	column SalesTerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 039ad86e-8848-4068-b7ee-a5894641a814
		sourceLineageTag: e2190568-d580-4d50-abaf-e366040afd52
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = User

	column Quantity
		dataType: int64
		formatString: #,0
		lineageTag: f08cb4fc-c761-47bd-a744-cb8629e50910
		sourceLineageTag: 1f8ac87e-c2b3-4d8f-bf03-f927b297974e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = User

	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7d2cca82-5719-4616-b455-d0fd373c7c92
		sourceLineageTag: 914c5056-0675-4279-90b9-9b47f4096186
		dataCategory: Uncategorized
		summarizeBy: average
		sourceColumn: Unit Price

		annotation SummarizationSetBy = User

	column Sales
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ed776f23-24a8-4f2f-9415-72345b3a8ee3
		sourceLineageTag: 4465de7d-4f58-462b-8ddb-6207fcce0d92
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = User

	/// Based in standard cost
	column Cost
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c41ed5a6-ee06-4a55-93e9-db1314b8d3cb
		sourceLineageTag: 4891cf60-2811-4a99-9d25-63cb318cbb38
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = User

	partition Sales = entity
		mode: directQuery
		source
			entityName: Sales
			expressionSource: 'DirectQuery to AS - 16-Starter-Sales Analysis antonio'

