table Targets
	lineageTag: f576cd6f-852c-40f0-a121-6e35b77eccb3
	sourceLineageTag: fc05aa02-32da-45a3-a497-78e97999d244

	measure Target = EXTERNALMEASURE("Target", CURRENCY, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ead03a86-4a3d-422d-8342-c8278db32067
		sourceLineageTag: ffc79c2c-8c37-499d-919a-2a3511102514
		dataCategory: Uncategorized

	measure Variance = EXTERNALMEASURE("Variance", CURRENCY, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ed519310-0f82-4316-8300-4ad09b3284ae
		sourceLineageTag: b4b78e5d-a649-4965-9c84-fae75fa12d98
		dataCategory: Uncategorized

	measure 'Variance Margin' = EXTERNALMEASURE("Variance Margin", DOUBLE, "DirectQuery to AS - 16-Starter-Sales Analysis antonio")
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 67c460e1-9362-4801-8ed1-0f3f0d00da2c
		sourceLineageTag: 35ad240b-b1a0-4fce-8c33-f0f9bb99044a
		dataCategory: Uncategorized

	column EmployeeID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1d323883-504d-44ce-a7a5-0e470b851e5d
		sourceLineageTag: 7552db63-13e7-4c1c-8e70-ee51dcd1066d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = User

	column TargetAmount
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8b037feb-86d2-4bf6-b913-6c38d88f9b94
		sourceLineageTag: c8642aff-9cd7-43b3-ad05-ba32d7661db3
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: TargetAmount

		annotation SummarizationSetBy = User

	column TargetMonth
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: b06bee23-90c4-42a2-99b3-6795f13476c7
		sourceLineageTag: 542d3ac9-7ec1-4b7a-8768-ea712b42a580
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: TargetMonth

		annotation SummarizationSetBy = User

	partition Targets = entity
		mode: directQuery
		source
			entityName: Targets
			expressionSource: 'DirectQuery to AS - 16-Starter-Sales Analysis antonio'

